### ISSUE TITLE
faulty TSV. 

### ISSUE THREAD

**Issue by brinwiththevlin** [brinwiththevlin/datavis_project_2#14]
the TSV Jillian provided seems to have some flaws. @linakaval  has brought it to my attention that there are about 200 entries without Service_request_id (unique identifier) but the original file from[this site]( https://data.cincinnati-oh.gov/Thriving-Neighborhoods/Cincinnati-311-Non-Emergency-Service-Requests/4cjh-bm8b) doesn't have the same issue. I see a need to create a new TSV before we continue

**Comment by linakaval** [comment]
ahh cool. I had a feeling

**Comment by linakaval** [comment]
also could we do a "|" delimited file? I don't think that char exists in the data. Might be more reliable than tab delimited
