### ISSUE TITLE
nice to have - map is hella laggy

### ISSUE THREAD

**Issue by brinwiththevlin** [brinwiththevlin/datavis_project_2#24]
a few things that I noticed. the map seems to be loading in for more than just the Cincinnati area which can contribute to lag. was wondering if there was a way to reduce the landscape that is viewable. 
also, note that it is easy to accidentally scroll through the map when trying to scroll through the web page itself. 
another thing that might contribute to lag is the `let vis = this;` line that is all over the place. If i am not mistaken i believe that this creates a new object every time.

**Comment by corncob567** [comment]
our map is the fastest map known to mankind
