### ISSUE TITLE
final A goal

### ISSUE THREAD

**Issue by brinwiththevlin** [brinwiththevlin/datavis_project_2#31]
**Choose one** of the following additional visualizations: 
* A visualization designed by your team showing the unstructured text data about the call and request.  This data is not available for all calls in the dataset, but if present, we want some representation of this unstructured text data, that gives the user an impression of the requests overall.  
  * As with the other charts, this should update when the user makes brushing selections
  * Sketch your approach, including encodings and interactions, and submit these sketches with your documentation. 
* Add the ability for the user to switch from the map view showing all the calls, to a view showing a heat-map representation, which displays the number of calls in each cell in a grid you create over the city.  
  * The heat map grid cells should size appropriately, as the user pans and zooms
  * Include tooltip interactions to show information about the calls in that grid cell 
  * Brushing and linking interactions in other visualizations should update your heatmap 
* Create a visualization which accomplishes an analysis task you are interested in exploring.  This visualization must be something 
  * other than a bar chart, line chart, pie chart or scatterplot.   
  * Clearly define the goals of this visualization- what do you want someone to learn from it?
  * Describe any data transformation you performed
  * Describe how you arrived at the selected visual encoding and interaction design.  Include sketchs
  * This visualization should be interactive and should tie-in with the interactions already created in your application (brushing and linking).

**Comment by brinwiththevlin** [comment]
I feel that the first option might be the easiest to do but it also looks like a lot of work from scratch, where as the second option we might be able to reuse part of the heatmap we already have. if we go the heatmap route we might need some reworking of the heatmap class.

**Comment by linakaval** [comment]
made some progress with word cloud, should be done friday
