### ISSUE TITLE
C - make timeline

### ISSUE THREAD

**Issue by linakaval** [brinwiththevlin/datavis_project_2#4]
TIMELINE: The page should include a timeline of when calls were placed over the complete timeframe.  This view of the data should allow someone to see when in the year most calls were placed. 
The timeline view should be clearly labeled, with axes that make it easy to interpret the data
The timeline view should be long enough to allow someone to see trends over time and variations in number of calls. 
You can binned into appropriate sized timeframes.  You can bin into an appropriate size interval- I would suggest daily or weekly, to give enough granularity in the timeline. 
Design choices:  Choose how you want to represent the data in this timeline.  Do you want to show a line chart, a bar chart, a heat-map, a plot of individual samples by time?  Draw a sketch of your intended visualization and explain your design choices. 
Choose how to use color for your timeline.  Are you using a neutral, desaturated color or a color scale?  Why did you make this choice?  
Details on demand: When hovering over the timeline, provide a tooltip to give the user more information about the timeframe they are hovering over.  For instance, if plotting the data by week, show the selected week and the number of calls.

**Comment by brinwiththevlin** [comment]
Is this just total calls by day? or is she asking that we make multiple lines/bars based on area? I guess I am confused about how this relates to the map

**Comment by brinwiththevlin** [comment]
So are we going to do the number of calls per day then? It doesn't make that big a difference what we do I just want to know what we are thinking before I start

**Comment by linakaval** [comment]
If we do # of calls a day, what do we want our viz to look like. Line chart? Histogram?
